<!doctype html>
<html lang="en">
	<head>
		<?= $this->fetch('/partials/header.phtml') ?>
	</head>
	<body>
		<?= $this->fetch('/partials/navbar.phtml', $navbar) ?>
		
		<div class="container-fluid">
			<div class="content">
				<div class="row">
					<div class="col-lg-12 p-0">
						<div class="card card-no-rounded">
							<div class="card-header d-flex justify-content-between">
								<span><b><i class="fa fa-pencil-ruler"></i> Planos</b></span>
							</div>
							<div class="card-body">
								
								<?php
							    if (isset($error_message))
								{
									echo '<h2>' . $error_message . '</h2>';
								}
								else
								{
							        $rowCounter = 0;
							        foreach($files as $key => $plan)
							        {
							            if (($rowCounter % 6) == 0) {
							                echo '<div class="row">';
							            }

										$d = new DateTime();
							            
								        echo '<div class="col-lg-2">';
								            echo '<div class="form-group">';
								                echo '<div name="' . $key . '">';
								                    echo '<img class="img-fluid rounded mx-auto d-block" name="file-image" src="' . ($plan->icon != "" ? $plan->icon : $plan->public_url) . '?' . $d->getTimestamp() . '">';
												    echo '<hr>';
												    echo '<label name="file-title"><b><a target="_blank" href="' . $plan->public_url . '">' . $plan->file_name . '</a></b></label>';
											    echo '</div>';
										    echo '</div>';
									    echo '</div>';
									    
									    if (($rowCounter % 6) == 5) {
							                echo '</div>';
							            }
									    
									    $rowCounter++;
							        }
								}
							    ?>
									
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
			
		<?= $this->fetch('/partials/libs.phtml') ?>
		
		<!-- Optional JavaScript -->
		<script>
		
			$(function() {
				
				// block UI on every ajax
				$(document)
					.ajaxStart(function(){
						$.blockUI({ message : null });
					})
					.ajaxStop(function(){
						$.unblockUI();
					});
				
				// device viewport
				configDeviceViewport();
					
				// create upload file dialog
				createUploadFileDialog();
				
				// attach events
				attachEvents();
				
				// device viewport
				function configDeviceViewport() {
					$("body").append('<div class="device-xs d-block d-sm-none"></div>');
					$("body").append('<div class="device-sm d-none d-sm-block d-md-none"></div>');
					$("body").append('<div class="device-md d-none d-md-block d-lg-none"></div>');
					$("body").append('<div class="device-lg d-none d-lg-block d-xl-none"></div>');
					$("body").append('<div class="device-xl d-none d-xl-block"></div>');
				}
				
				// create upload file dialog
				function createUploadFileDialog() {
					
					var htmlDialog = 
						'<div class="d-none" name="upload-file-dialog" title="Cargar PDF">' +
							'<div class="row">' +
								'<div class="col-12">' +
									'<div class="form-group">' +
										'<input class="form-control-file" type="file" accept=".pdf" name="upload-file-input" accept="image/*;capture=camera">' +
									'</div>' +
									// '<div class="form-group">' +
									// 	'<img class="img-fluid rounded mx-auto d-block" name="upload-file-image">' +
									// '</div>' +
								'</div>' +
							'</div>' +
						'</div>';

					$("body").append(htmlDialog);
					
					$('div[name="upload-file-dialog"]').dialog({
						resizable: false,
						height: "auto",
						modal: true,
						autoOpen: false,
						position: { my: "center", at: "top", of: window },
						buttons: {
						    Borrar: function()
						    {
						        var guid    = $(this).dialog("option", "guid");
						        var dialog 	= $(this);
						        
						        $.ajax({
									method: 'POST',
									url: `/plans/delete/${guid}`, // point to server-side PHP script 
									success: function(data, textStatus, jqXHR)
									{
										if (data.Result == 'OK')
										{
										    // update base image
										    d = new Date();
											$('div[name="' + guid + '"] > img[name="file-image"]').attr("src", data.File.public_url + "?"+d.getTime());
											$('div[name="' + guid + '"] > label[name="file-title"] > b > a').text("");
										    
											dialog.dialog("close");
											
											$.stdShowMessage({
												icon: 'fa fa-check',
												message: '¡Archivo borrado!',
												type: 'success'
											});
										}
										else if (data.Result == 'ERROR') {
											$.stdShowMessage({
												icon: 'fa fa-exclamation-triangle',
												message: 'No pudimos borrar el archivo. Por favor, vuelva a intenterlo.',
												type: 'warning'
											});
										}
									},
									error: function(jqXHR, textStatus, errorThrown) {
										console.warn(jqXHR.responseText);
									},
								});
						    },
							Cancelar: function() {
								$(this).dialog("close");
							},
							Guardar: function() {
								var guid 	= $(this).dialog("option", "guid");
								var dialog 	= $(this);
								
								// var image 	= $('img[name="upload-file-image"]');
								var input   = $('input[name="upload-file-input"]')[0];
								
								if (input.files && input.files[0])
								{
									var filename = input.files[0];
								}
								else
								{
									$.stdShowMessage({
										icon: 'fa fa-exclamation-triangle',
										message: 'Debe seleccionar un archivo para continuar.',
										type: 'warning'
									});
									return;
								}
										
								var formData = new FormData();
								formData.append('plan_file', filename);
							
								$.ajax({
									method: 'POST',
									url: `/plans/upload/${guid}`, // point to server-side PHP script 
									dataType: 'text',  // what to expect back from the PHP script, if anything
									cache: false,
									contentType: false,
									processData: false,
									data: formData,
									beforeSend : function() {
										$.blockUI({ message: null });
									}, 
									success: function(data, textStatus, jqXHR)
									{
										data = JSON.parse(data);
										if (data.Result == 'OK')
										{
											// update base image
											d = new Date();
											$('div[name="' + guid + '"] > img[name="file-image"]').attr("src", `${data.File.icon}?${d.getTime()}`);
											$('div[name="' + guid + '"] > label[name="file-title"] > b > a').text(filename.name);
											$('div[name="' + guid + '"] > label[name="file-title"] > b > a').attr("href", `${data.File.public_url}?${d.getTime()}`);
											
											dialog.dialog("close");
											
											$.stdShowMessage({
												icon: 'fa fa-check',
												message: '¡Proceso finalizado!',
												type: 'success'
											});
										}
										else if (data.Result == 'ERROR') {
											$.stdShowMessage({
												icon: 'fa fa-exclamation-triangle',
												message: 'No pudimos subir el archivo. Por favor, vuelva a intenterlo.',
												type: 'warning'
											});
										}
										$.unblockUI();
									},
									error: function(jqXHR, textStatus, errorThrown) {
										$.unblockUI();
										console.warn(jqXHR.responseText);
									},
								});
							},
						},
						create: function() {
                            $(this).closest(".ui-dialog")
                                    .find(".ui-button:nth-child(1)") // the first button
                                    .addClass("bg-danger text-white");

							$(this).removeClass("d-none");
						},
					});
				}
				
				// attach events
				function attachEvents() 
				{
					// on click match photo button
					$('img[name="file-image"]').on('click', function(e) {
						var guid = $(this).parent().attr('name');					
						showUploadFileDialog(guid);
					});
					
				    // on change photo input
    				// $(document).on('change', 'input[name="upload-file-input"]', function(e) {
    					
    				// 	var input = $(this)[0];
    				// 	if (input.files && input.files[0])
    				// 	{
    				// 		var reader = new FileReader();
    				// 		reader.onload = function(e) {
    				// 			$('img[name="upload-file-image"]').attr('src', e.target.result);
    				// 		}
    				// 		reader.readAsDataURL(input.files[0]);
    				// 	}
    				// });
				}
				
				// check viewport
				function isBreakpoint(alias) {
					return $('.device-' + alias).is(':visible');
				}
				
				// show upload file dialog
				function showUploadFileDialog(guid) {
					
					// define dialog width
					var dialogWidth = "40%";
					if (isBreakpoint('sm') || isBreakpoint('xs')) {
						dialogWidth = "100%";
					}

					// clear input text
					$('input[name="upload-file-input"]').val("");
					
					// load photo from server if exists
					$.ajax({
						method: 'POST',
						url: `/plans/download/${guid}`,
						beforeSend : function() {
							// empty photo
							//$('img[name="upload-file-image"]').attr("src", "");
							// resetCropper();
						}, 
						success: function(data, textStatus, jqXHR)
						{
							if (data.Result == 'OK')
							{
								// var d = new Date();
								// $('img[name="upload-file-image"]').attr("src", `${data.File.public_url}?${d.getTime()}`);
								
								$('div[name="upload-file-dialog"]')
            						.dialog("option", "guid", guid)
            						.dialog({ width : dialogWidth })
            						.dialog("open");
							}
						},
						error: function(jqXHR, textStatus, errorThrown) {
							console.warn(jqXHR.responseText);
						},
					});
				}
				
			});
		</script>
	</body>
</html>