<!doctype html>
<html lang="en">
	<head>
		<?= $this->fetch('/partials/header.phtml') ?>
	</head>
	<body>
		<?= $this->fetch('/partials/navbar.phtml', $navbar) ?>
		
		<?php $suppliers_enabled 		= (isset($suppliers) and count($suppliers) > 0); ?>
		<?php $documentsTypes_enabled	= (isset($documentsTypes) and count($documentsTypes) > 0); ?>
		<?php $productsState_enabled	= (isset($productsState) and count($productsState) > 0); ?>
		
		<div class="container-fluid">
			<div class="content">
				<div class="row">
					<div class="col-lg-12 p-0">
						<div class="card card-no-rounded">
							<div class="card-header d-flex justify-content-between">
								<span><b><i class="fa fa-truck-loading"></i> Recepción de Mercadería</b></span>
							</div>
							<div class="card-body">
								<div class="row">
									<div class="col-lg-3 col-md-6">
										<div class="form-group">
											<label class="font-weight-bold">Proveedores:</label>
											<br>
											<label <?= !$suppliers_enabled ? '' : 'class="d-none" ' ?>name="suppliers-label"><i class="fa fa-exclamation-triangle"></i> No hay proveedores disponibles!</label>
											<select class="form-control<?= $suppliers_enabled ? '' : ' d-none' ?>" name="suppliers-select" multiple="multiple">
											<?php if ($suppliers_enabled) : ?>
											<?php foreach($suppliers as $supplier) : ?>
												<option value="<?= $supplier->id ?>">
													<?= $supplier->unique_code . ' | ' . $supplier->business_name ?>
												</option>
											<?php endforeach; ?>
											<?php endif; ?>
											</select>
										</div>
									</div>
									
									<div class="col-lg-3 col-md-6">
										<div class="form-group">
											<label class="font-weight-bold">Comprobantes:</label>
											<br>
											<label <?= !$documentsTypes_enabled ? '' : 'class="d-none" ' ?>name="docs-types-label"><i class="fa fa-exclamation-triangle"></i> No hay documentos disponibles!</label>
											<select class="form-control<?= $documentsTypes_enabled ? '' : ' d-none' ?>" name="docs-types-select" multiple="multiple">
											<?php if ($documentsTypes_enabled) : ?>
											<?php foreach($documentsTypes as $documentType) : ?>
												<option
													value="<?= $documentType->unique_code ?>">
													<?= trim($documentType->description) ?>
												</option>
											<?php endforeach; ?>
											<?php endif; ?>
											</select>
										</div>
									</div>

									<div class="col-lg-3 col-md-6">
										<div class="form-group">
											<label class="font-weight-bold">Estados:</label>
											<br>
											<label <?= !$productsState_enabled ? '' : 'class="d-none" ' ?>name="products-state-label"><i class="fa fa-exclamation-triangle"></i> No hay estados disponibles!</label>
											<select class="form-control<?= $productsState_enabled ? '' : ' d-none' ?>" name="products-state-select" multiple="multiple">
											<?php if ($productsState_enabled) : ?>
											<?php foreach($productsState as $status) : ?>
												<option
													value="<?= $status->id ?>"
													<?= $status->selected ? "selected" : "" ?>
													>
													<?= trim($status->description) ?>
												</option>
											<?php endforeach; ?>
											<?php endif; ?>
											</select>
										</div>
									</div>
								</div>
								
								<div class="row">
							        <div class="col">
										<div class="btn btn-outline-primary" name="btn-search"><i class="fa fa-search"></i> Buscar</div>
									<div>
								</div>
							
							    <div class="row">
							        <div class="col">
							            <div name="table-content" class="table-responsive-sm small"></div>
							        </div>
							    </div>
							</div>
						</div>
					</div>
				</div>
				
			</div>
		</div>
			
		<?= $this->fetch('/partials/libs.phtml') ?>
		
		<!-- Optional JavaScript -->
		<script>
			$(function(){
				
				if ( !$('select[name="suppliers-select"]').hasClass('d-none') )
					$('select[name="suppliers-select"]').select2({ width: '100%' });
				
				if ( !$('select[name="docs-types-select"]').hasClass('d-none') )
					$('select[name="docs-types-select"]').select2({ width: '100%' });

				if ( !$('select[name="products-state-select"]').hasClass('d-none') )
					$('select[name="products-state-select"]').select2({ width: '100%' });
				
				// table-content
				$('div[name="table-content"]').jtable({
					title: ' ',
					columnSelectable: false,
					showCommandButtons: false,
					paging: true,
					pageList: 'normal',
					pageSize: 10,
					actions: {
						listAction: '/purchases/delivery/read',
						updateAction: '/purchases/delivery/update',
						},
					fields: {
						id: {
							key: true,
							create: false,
							edit: false,
							list: false
						},
						menu: {
							title: '',
							width: '7%',
							edit: false,
							create: false,
							display: function (data) {
								return '<span class="btn btn-light btn-sm" name="btn-table-context-menu" data-record-key="' + data.record.id + '"><i class="fa fa-ellipsis-v"></i></span>';
							},
						},
						// doc_type_code: {
						// 	title: 'Comp.',
						// 	width: '5%',
						// 	edit: false,
						// 	display: function(data){
						// 		return data.record.purchase_header.document_type_code;
						// 	}
						// },
						supplier_description: {
							title: 'Proveedor',
							width: '10%',
							edit: false,
							display: function(data){
								return data.record.purchase_header.supplier.business_name;
							}
						},
						number: {
							title: 'Número',
							width: '10%',
							edit: false,
							listClass: 'd-lg-table-cell',
							display: function(data){
								return data.record.purchase_header.number;
							}
						},
						product_description: {
							title: 'Detalle',
							width: '20%',
							edit: false,
							listClass: 'd-lg-table-cell',
						},
						delivery_date: {
							title: 'F. Entrega',
							width: '10%',
							edit: false,
							display: function(data) {
								if (data.record.delivery_date) {
									US_Date = new Date(data.record.delivery_date);
									US_Date.setHours(US_Date.getHours() + 3); // AR_Date
									return US_Date.toLocaleDateString();
								}
								return 'Sin fecha';
							},
						},
						quantity: {
							title: 'Cant.',
							width: '5%',
							edit: false,
						},
						product_unit: {
							title: 'Uni. Med.',
							width: '5%',
							edit: false,
							options: '/products_units/options',
						},
						more_info: {
							title: 'Más info',
							width: '20%',
							edit: false,
						},
						status_id: {
							title: 'Estado',
							width: '15%',
							options: '/products_state/options',
							inputClass: 'form-control',
						},
					}
				});
		 
				//Load list from server
				//$('div[name="table-content"]').jtable('load');
				
				// click on search
				$('div[name="btn-search"]').on('click', function(e) {
					e.preventDefault();

					$('div[name="table-content"]').jtable('load', { 
						suppliers_ids : $('select[name="suppliers-select"]').val(),
						docs_types_codes : $('select[name="docs-types-select"]').val(),
						products_state_ids : $('select[name="products-state-select"]').val(),
					});
				});

				$('div[name="btn-search"]').click();
				
				// Add Bootstrap style to jTable
				$.stdjTableBootstrapStyle();
				
				// Context Menu
				$.contextMenu({
					selector: 'span[name="btn-table-context-menu"]',
					trigger: 'left',
					items: {
						"edit_status": {
							name: '<span><i class="fa fa-edit"></i> Cambiar Estado</span>',
							isHtmlName: true,
							callback: function(itemKey, opt, e) {
								$row = $('tr.jtable-data-row[data-record-key="' + opt.$trigger.attr('data-record-key') + '"]');
								$('div[name="table-content"]').jtable('showEditForm', $row);
								return true;
							},
						},
						"fotos": {
							name: '<span><i class="fa fa-camera-retro"></i> Fotos</span>',
							isHtmlName: true,
							callback: function(itemKey, opt, e) {
								// window.location.href = '/purchases/delivery/pictures/' + opt.$trigger.attr('data-record-key');
								window.open('/purchases/delivery/pictures/' + opt.$trigger.attr('data-record-key'), '_blank');
								return false;
							},
						},
					}
				});
				
			});
		</script>
	</body>
</html>